name: Cleanup Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete last artifact
        uses: geekyeggo/delete-artifact@v4
        with:
          name: |
            *
          useGlob: true
